"""New

Revision ID: 2b1009de062f
Revises: f9c02f4a8d68
Create Date: 2024-05-30 16:05:34.788005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b1009de062f'
down_revision = 'f9c02f4a8d68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
